import {useEffect,useRef,useState} from 'react';

const formats={square:{label:'1:1',width:1080,height:1080},story:{label:'9:16',width:1080,height:1920},wide:{label:'16:9',width:1600,height:900}};
const validScenes=new Set(['rumah','kampung','sekolah','kota','digital']);
const BASE=import.meta.env.BASE_URL||'/';
const wrap=(ctx,text,maxWidth)=>{const words=String(text||'').trim().split(/\s+/);const rows=[];let line='';for(const word of words){const next=(line+' '+word).trim();if(ctx.measureText(next).width>maxWidth&&line){rows.push(line);line=word}else line=next}if(line)rows.push(line);return rows.slice(0,5)};
const loadImage=src=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src});
function drawCover(ctx,image,W,H){const scale=Math.max(W/image.naturalWidth,H/image.naturalHeight),w=image.naturalWidth*scale,h=image.naturalHeight*scale;ctx.drawImage(image,(W-w)/2,(H-h)/2,w,h)}
function canvasBlob(canvas){return new Promise(resolve=>canvas.toBlob(resolve,'image/png',.94))}

export default function MemoryCardStudio({year=1995,scene='rumah'}){
 const [format,setFormat]=useState('square');const [message,setMessage]=useState('Saya kembali ke dunia yang pernah kita tinggali.');const [name,setName]=useState('Anak 90-an');const [cardYear,setCardYear]=useState(year);const [status,setStatus]=useState('Artwork dirender lokal sebagai PNG. Tidak ada upload server.');const canvasRef=useRef(null);
 const spec=formats[format];const sceneId=validScenes.has(scene)?scene:'rumah';

 useEffect(()=>{let cancelled=false;async function render(){const canvas=canvasRef.current;if(!canvas)return;canvas.width=spec.width;canvas.height=spec.height;const ctx=canvas.getContext('2d');if(!ctx)return;const W=spec.width,H=spec.height,p=Math.round(W*.07);ctx.clearRect(0,0,W,H);try{const image=await loadImage(`${BASE}assets/world/raster/${sceneId}-sore.webp`);if(cancelled)return;drawCover(ctx,image,W,H)}catch{ctx.fillStyle='#081210';ctx.fillRect(0,0,W,H)}
  const wash=ctx.createLinearGradient(0,0,W,H);wash.addColorStop(0,'rgba(5,14,12,.86)');wash.addColorStop(.48,'rgba(8,20,17,.66)');wash.addColorStop(1,'rgba(35,25,17,.82)');ctx.fillStyle=wash;ctx.fillRect(0,0,W,H);
  const glow=ctx.createRadialGradient(W*.78,H*.2,0,W*.78,H*.2,W*.46);glow.addColorStop(0,'rgba(118,225,212,.22)');glow.addColorStop(1,'rgba(118,225,212,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);
  ctx.strokeStyle='rgba(224,192,119,.42)';ctx.lineWidth=Math.max(2,W*.0018);ctx.beginPath();const r=W*.035;ctx.roundRect(p,p,W-p*2,H-p*2,r);ctx.stroke();
  ctx.fillStyle='#82ddd2';ctx.font=`700 ${Math.round(W*.023)}px ui-monospace, monospace`;ctx.letterSpacing='2px';ctx.fillText('WISATA MASA LALU / INDONESIA 90-AN',p,p+Math.round(H*.055));
  const titleY=Math.round(H*.31);ctx.fillStyle='#dfc37d';ctx.font=`700 ${Math.round(W*.025)}px ui-monospace, monospace`;ctx.fillText('SAYA KEMBALI KE',p,titleY-Math.round(H*.075));
  ctx.fillStyle='#f5eee1';ctx.font=`600 ${Math.round(W*(format==='wide'?.115:.15))}px Georgia, serif`;ctx.fillText(String(cardYear),p,titleY);
  ctx.fillStyle='#f1eadf';ctx.font=`500 ${Math.round(W*(format==='wide'?.038:.048))}px Georgia, serif`;const rows=wrap(ctx,message,W-p*2);const gap=Math.round(H*.062);rows.forEach((row,index)=>ctx.fillText(row,p,titleY+Math.round(H*.13)+index*gap));
  ctx.fillStyle='#86dcd2';ctx.font=`700 ${Math.round(W*.026)}px ui-monospace, monospace`;ctx.fillText(String(name||'Anak 90-an').toUpperCase().slice(0,32),p,H-p-72);
  ctx.fillStyle='rgba(240,229,207,.62)';ctx.font=`600 ${Math.round(W*.018)}px ui-monospace, monospace`;ctx.fillText(`${sceneId.toUpperCase()} · BUKAN MEMBACA MASA LALU. MASUK KEMBALI KE DALAMNYA.`,p,H-p-30);
  ctx.globalAlpha=.05;for(let i=0;i<Math.round(W*H/5600);i++){ctx.fillStyle=Math.random()>.5?'#fff':'#000';ctx.fillRect(Math.random()*W,Math.random()*H,1+Math.random()*2,1+Math.random()*2)}ctx.globalAlpha=1;
 }
 render();return()=>{cancelled=true}},[spec,format,message,name,cardYear,sceneId]);

 async function download(){const canvas=canvasRef.current;if(!canvas)return;const blob=await canvasBlob(canvas);if(!blob){setStatus('PNG tidak dapat dibuat pada browser ini.');return}const href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=`wisata-masa-lalu-${cardYear}-${format}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);setStatus('Kartu PNG resolusi tinggi tersimpan di perangkat.')}
 async function share(){const canvas=canvasRef.current;if(!canvas)return;const blob=await canvasBlob(canvas);const text=`Saya kembali ke ${cardYear} lewat Wisata Masa Lalu — Indonesia 90-an.`;try{if(blob&&navigator.share){const file=new File([blob],`wisata-masa-lalu-${cardYear}.png`,{type:'image/png'});if(!navigator.canShare||navigator.canShare({files:[file]})){await navigator.share({title:'Wisata Masa Lalu',text,files:[file]});setStatus('Artwork PNG berhasil dibagikan.');return}}await navigator.clipboard.writeText(text);setStatus('Teks berbagi disalin. PNG tetap dapat disimpan dari tombol di sebelahnya.')}catch{setStatus('Berbagi dibatalkan. Artwork tetap aman di perangkat.')}}
 return <div className="memory-card-studio"><section className="memory-card-controls"><small>MEMORY CARD GENERATOR / LOCAL PNG</small><h3>Satu kartu, satu pintu pulang.</h3><label>Tahun<select value={cardYear} onChange={e=>setCardYear(Number(e.target.value))}>{Array.from({length:10},(_,i)=>1990+i).map(value=><option key={value}>{value}</option>)}</select></label><label>Nama / julukan<input value={name} onChange={e=>setName(e.target.value.slice(0,32))} maxLength="32"/></label><label>Kalimat<input value={message} onChange={e=>setMessage(e.target.value.slice(0,140))} maxLength="140"/></label><div className="card-format" role="group" aria-label="Format kartu">{Object.entries(formats).map(([id,item])=><button key={id} type="button" aria-pressed={format===id} onClick={()=>setFormat(id)}>{item.label}</button>)}</div><div className="card-actions"><button type="button" onClick={download}>Simpan PNG</button><button type="button" onClick={share}>Bagikan PNG</button></div><output role="status">{status}</output></section><figure className={`memory-card-preview ${format}`}><canvas ref={canvasRef} aria-label={`Preview kartu nostalgia tahun ${cardYear}`}/><figcaption>{spec.width} × {spec.height} · PNG raster · scene WebP premium · tanpa upload server</figcaption></figure></div>;
}
