import {useMemo,useState} from 'react';

const formats={square:{label:'1:1',width:1080,height:1080},story:{label:'9:16',width:1080,height:1920},wide:{label:'16:9',width:1600,height:900}};
const escapeXml=value=>String(value||'').replace(/[<>&'\"]/g,char=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[char]));
function wrap(text,max=34){const words=String(text||'').trim().split(/\s+/);const rows=[];let line='';for(const word of words){const next=(line+' '+word).trim();if(next.length>max&&line){rows.push(line);line=word}else line=next}if(line)rows.push(line);return rows.slice(0,5)}

export default function MemoryCardStudio({year=1995,scene='rumah'}){
 const [format,setFormat]=useState('square');const [message,setMessage]=useState('Saya kembali ke dunia yang pernah kita tinggali.');const [name,setName]=useState('Anak 90-an');const [cardYear,setCardYear]=useState(year);const [status,setStatus]=useState('Semua proses terjadi di perangkatmu.');
 const spec=formats[format];
 const svg=useMemo(()=>{const W=spec.width,H=spec.height,p=Math.round(W*.07),rows=wrap(message,format==='story'?28:format==='wide'?48:34),titleY=Math.round(H*.32),lineGap=Math.round(H*.062);return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#081210"/><stop offset=".52" stop-color="#11201d"/><stop offset="1" stop-color="#2d2418"/></linearGradient><radialGradient id="g"><stop stop-color="#87e4d8" stop-opacity=".24"/><stop offset="1" stop-color="#87e4d8" stop-opacity="0"/></radialGradient><filter id="grain"><feTurbulence baseFrequency=".8" numOctaves="2" seed="17"/><feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 .07 0"/></filter></defs><rect width="${W}" height="${H}" fill="url(#bg)"/><circle cx="${W*.76}" cy="${H*.2}" r="${W*.35}" fill="url(#g)"/><rect x="${p}" y="${p}" width="${W-p*2}" height="${H-p*2}" rx="${Math.round(W*.035)}" fill="none" stroke="#d6bd7a" stroke-opacity=".35" stroke-width="2"/><text x="${p}" y="${p+42}" fill="#83ddd2" font-family="monospace" font-size="${Math.round(W*.024)}" letter-spacing="4">WISATA MASA LALU / INDONESIA 90-AN</text><text x="${p}" y="${titleY-Math.round(H*.08)}" fill="#dcc27e" font-family="monospace" font-size="${Math.round(W*.026)}" letter-spacing="3">SAYA KEMBALI KE</text><text x="${p}" y="${titleY}" fill="#f5eee1" font-family="Georgia,serif" font-size="${Math.round(W*(format==='wide'?.115:.15))}" font-weight="700">${cardYear}</text>${rows.map((row,index)=>`<text x="${p}" y="${titleY+Math.round(H*.13)+index*lineGap}" fill="#f1eadf" font-family="Georgia,serif" font-size="${Math.round(W*(format==='wide'?.038:.048))}">${escapeXml(row)}</text>`).join('')}<text x="${p}" y="${H-p-72}" fill="#86dcd2" font-family="monospace" font-size="${Math.round(W*.026)}">${escapeXml(name.toUpperCase())}</text><text x="${p}" y="${H-p-30}" fill="#f0e5cf" fill-opacity=".56" font-family="monospace" font-size="${Math.round(W*.019)}">${escapeXml(scene.toUpperCase())} · BUKAN MEMBACA MASA LALU. MASUK KEMBALI KE DALAMNYA.</text><rect width="${W}" height="${H}" filter="url(#grain)" opacity=".55"/></svg>`},[spec,format,message,name,cardYear,scene]);
 const url=useMemo(()=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`,[svg]);
 function download(){const blob=new Blob([svg],{type:'image/svg+xml'}),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=`wisata-masa-lalu-${cardYear}-${format}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);setStatus('Kartu disimpan sebagai SVG resolusi tinggi.')}
 async function share(){const text=`Saya kembali ke ${cardYear} lewat Wisata Masa Lalu — Indonesia 90-an.`;try{if(navigator.share){await navigator.share({title:'Wisata Masa Lalu',text});setStatus('Kartu nostalgia siap dibagikan.');return}await navigator.clipboard.writeText(text);setStatus('Teks berbagi disalin ke clipboard.')}catch{setStatus('Berbagi dibatalkan. Kartu tetap aman di perangkat.') }}
 return <div className="memory-card-studio"><section className="memory-card-controls"><small>MEMORY CARD GENERATOR / LOCAL</small><h3>Satu kartu, satu pintu pulang.</h3><label>Tahun<select value={cardYear} onChange={e=>setCardYear(Number(e.target.value))}>{Array.from({length:10},(_,i)=>1990+i).map(value=><option key={value}>{value}</option>)}</select></label><label>Nama / julukan<input value={name} onChange={e=>setName(e.target.value.slice(0,32))} maxLength="32"/></label><label>Kalimat<input value={message} onChange={e=>setMessage(e.target.value.slice(0,140))} maxLength="140"/></label><div className="card-format" role="group" aria-label="Format kartu">{Object.entries(formats).map(([id,item])=><button key={id} type="button" aria-pressed={format===id} onClick={()=>setFormat(id)}>{item.label}</button>)}</div><div className="card-actions"><button type="button" onClick={download}>Simpan kartu</button><button type="button" onClick={share}>Bagikan</button></div><output role="status">{status}</output></section><figure className={`memory-card-preview ${format}`}><img src={url} alt={`Preview kartu nostalgia tahun ${cardYear}`}/><figcaption>{spec.width} × {spec.height} · vector high-resolution · tanpa upload server</figcaption></figure></div>;
}
